config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root "home#index"

  get "home", to: "home#index"

  resources :blagues, only: [:show, :index, :new, :create, :edit, :update, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blague.rb
class Blague < ApplicationRecord

  validates :nom, presence: true
  validates :contenu, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blagues_controller.rb
class BlaguesController < ApplicationController

  def index
    @blague = Blague.all
  end


  def show
    @blague = Blague.find(params[:id])
  end

  def new
    @blague = Blague.new()
  end

  def edit
    @blague = Blague.find(params[:id])
  end

  def create
    @blague = Blague.new(blagues_params)

    if @blague.save
      redirect_to blagues_path
    else
      render :new
    end
  end

  def update
    @blague = Blague.find(params[:id])
    if @blague.update(blagues_params)
      redirect_to blagues_path
    else
      render :edit
    end
  end

  def destroy
    @blague = Blague.find(params[:id])
    @blague.destroy
    redirect_to blagues_path
  end

  private
  def blagues_params
    params.require(:blague).permit(:nom, :contenu, :auteur)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/blagues/edit.html.erb
<h2>Modifier la blague</h2>

<%= form_with model: @blague, local: true do |form| %>

  <p>
    <%= form.label "Nom de blague :" %>
    <br />
    <%= form.text_field :nom %>
  </p>

  <p>
    <%= form.label "Saisir la blague" %>
    <br />
    <%= form.text_area :contenu %>
  </p>

  <p>
    <%= form.label "Qui a écrit cette blague ?" %>
    <br />
    <%= form.text_field :auteur %>
  </p>

  <p>
    <br />
    <%= form.submit "Valider les modificaations"%>
  </p>

<% end %>

app/views/blagues/index.html.erb
<div>Voici toutes les blagues : </div>
<br />

<% @blague.each do |blague| %>
  <div>Nom : <%= blague.nom%></div>
  <div>Contenu : <%= blague.contenu%></div>
  <div>Rédigé par : <%= blague.auteur%></div>
  <div><%= link_to "Voir plus", blague_path(blague) %></div>
  <div><%= link_to "Modifier", edit_blague_path(blague) %></div>
  <div><%= button_to "Supprimer la blague", blague_path(blague), method: :delete %></div>
  <br />
<%end%>

<div><%= link_to "Créer votre blague !", new_blague_path()%></div>

app/views/blagues/new.html.erb
<h2>Publier une nouvelle blague</h2>

<%= form_with model: @blague, local: true do |form| %>

  <% if @blague.errors.any? %>

    <h2>Une erreur est survenue</h2>

    <ul>
      <% @blague.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>

  <% end %>

  <p>
    <%= form.label "Nom de blague :" %>
    <br />
    <%= form.text_field :nom %>
  </p>

  <p>
    <%= form.label "Saisir la blague" %>
    <br />
    <%= form.text_area :contenu %>
  </p>

  <p>
    <%= form.label "Qui a écrit cette blague ?" %>
    <br />
    <%= form.text_field :auteur %>
  </p>

  <p>
    <br />
    <%= form.submit "Publier"%>
  </p>

<% end %>

app/views/blagues/show.html.erb
<div>Blague : <%= @blague.nom %></div>
<div> <%= @blague.contenu %></div>
<div> Auteur : <%=@blague.auteur%></div>
<br />
<div><a href="/blagues">Revenir</a></div>

app/views/home/index.html.erb
<div>Page d'accueil</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PremierSite</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>